secret:
  key: EU_SEI_NAO

spring:
  datasource:
    url: jdbc:h2:mem:teste
    username: sa
    password: password
    driverClassName: org.h2.Driver
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        format_sql: true